modLoader="javafml"
loaderVersion="[40,)"
license="Public Domain"

[[mods]]
modId="espada_amatista"
version="1.1.2"
displayName="Amethyts Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/amethyst-tool-kit"
logoFile="logo.png"
authors="greengamer32"

[[dependencies.espada_amatista]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




